### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by ItsProfessional**
- Add option to prevent adobe processes and services from starting automatically
- Add option to hide Creative Cloud Files from File Explorer
- Add option to hide the trial banner
- Also stop services in ProcessKill.ps1
- Remove repetitive code
- Replace "taskkill" with "Stop-Process" and ">$null" with "Out-Null" in ProcessKill.ps1
- Remove unnecessary ".exe" text
- Fix wording, indents and caps in many places
- Fix bug in acrobatfix.bat where it would restart no matter which option you chose in the restart prompt
- Explicitly set current directory to the script's directory in CCStopper.bat (So the script works if someone ran it as administrator, as doing that would make the current directory system32 instead of the script directory)
- Restart immediately instead of after 60 seconds in AcrobatFix.bat

### CODE REVIEW

**Comment by eaaasun** [comment]
Thanks for cleaning up code/adding new functionality! Merged to the development branch to tidy up the menus and make sure things work as they should.

**Comment by eaaasun** [comment]
What is the intended outcome of the TrialRemove script? I'm not sure as I haven't noticed any changes within adobe apps or the creative cloud app after running it. 

It returns these errors:
```
gc : Cannot find path 'C:\Program Files\Common Files\Adobe\UXP\extensions\com.adobe.ccx.start-5.9.0\css\styles.css'
because it does not exist.
At line:1 char:2
+ (gc 'C:\Program Files\Common Files\Adobe\UXP\extensions\com.adobe.ccx ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...\css\styles.css:String) [Get-Content], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Out-File : Could not find a part of the path 'C:\Program Files\Common
Files\Adobe\UXP\extensions\com.adobe.ccx.start-5.9.0\css\styles.css.bak'.
At line:1 char:102
+ ... les.css') | Out-File -encoding ASCII 'C:\Program Files\Common Files\A ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

Get-Content : Cannot find path 'C:\Program Files\Common
Files\Adobe\UXP\extensions\com.adobe.ccx.start-5.9.0\css\styles.css' because it does not exist.
At D:\Code\CCStopper\scripts\TrialRemove.ps1:31 char:2
+ (Get-Content $StylePath -Raw) -replace $Style_TrialExpiresBanner, $St ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...\css\styles.css:String) [Get-Content], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Get-Content : Cannot find path 'C:\Program Files\Adobe\Adobe Photoshop
2022\Required\UXP\com.adobe.ccx.start\css\styles.css' because it does not exist.
At D:\Code\CCStopper\scripts\TrialRemove.ps1:32 char:2
+ (Get-Content $StylePath1 -Raw) -replace $Style_TrialExpiresBanner, $S ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...\css\styles.css:String) [Get-Content], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Get-Content : Cannot find path 'C:\Program Files\Adobe\Adobe Illustrator 2022\Support
Files\Required\UXP\extensions\com.adobe.ccx.start\css\styles.css' because it does not exist.
At D:\Code\CCStopper\scripts\TrialRemove.ps1:33 char:2
+ (Get-Content $StylePath2 -Raw) -replace $Style_TrialExpiresBanner, $S ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...\css\styles.css:String) [Get-Content], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Get-Content : Cannot find path 'C:\Program Files\Common
Files\Adobe\UXP\extensions\com.adobe.ccx.start-5.9.0\css\styles.css' because it does not exist.
At D:\Code\CCStopper\scripts\TrialRemove.ps1:34 char:2
+ (Get-Content $StylePath -Raw) -replace $Style_TrialEnded, $Style_None ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...\css\styles.css:String) [Get-Content], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Get-Content : Cannot find path 'C:\Program Files\Adobe\Adobe Photoshop
2022\Required\UXP\com.adobe.ccx.start\css\styles.css' because it does not exist.
At D:\Code\CCStopper\scripts\TrialRemove.ps1:35 char:2
+ (Get-Content $StylePath1 -Raw) -replace $Style_TrialEnded, $Style_Non ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...\css\styles.css:String) [Get-Content], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Get-Content : Cannot find path 'C:\Program Files\Adobe\Adobe Illustrator 2022\Support
Files\Required\UXP\extensions\com.adobe.ccx.start\css\styles.css' because it does not exist.
At D:\Code\CCStopper\scripts\TrialRemove.ps1:36 char:2
+ (Get-Content $StylePath2 -Raw) -replace $Style_TrialEnded, $Style_Non ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...\css\styles.css:String) [Get-Content], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand
```

**Comment by eaaasun** [comment]
Did some more digging... Turns out, I don't have com.adobe.ccx.start-5.9.0 as I have not updated the creative cloud desktop app. I also have all my adobe apps installed on a different drive, so this patch won't work in my case.

**Comment by ItsProfessional** [comment]
Oh sorry I did not get a notification when you commented this, you can fix this by selecting the folder that starts with com.adobe.ccx.start so it works with every version
I am working on it

**Pull request merged**
